CREATE DATABASE IF NOT EXISTS OCA_Registro_Actividades;
USE OCA_Registro_Actividades;

CREATE TABLE IF NOT EXISTS rol (
    ID_ROL INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(20) NOT NULL,
    DESCRIPCION VARCHAR(20),
    ESTADO ENUM('activo', 'inactivo') DEFAULT 'activo'
);

CREATE TABLE IF NOT EXISTS departamento (
    ID_DEPARTAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS ciudad (
    ID_CIUDAD INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS localidad (
    ID_LOCALIDAD INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS zona (
    ID_ZONA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS clientes (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(20) NOT NULL,
    DIRECCION VARCHAR(30) NOT NULL,
    TELEFONO VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS cuenta (
    ID_CUENTA_cliente INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO_CUENTA VARCHAR(20) NOT NULL,
    ID_CLIENTE INT NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES clientes(ID_CLIENTE) ON DELETE CASCADE; 
);

CREATE TABLE IF NOT EXISTS actividad (
    ID_ACTIVIDAD INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(25) NOT NULL,
    DESCRIPCION VARCHAR(150) NOT NULL, 
);

CREATE TABLE IF NOT EXISTS materiales (
    ID_MATERIAL INT PRIMARY KEY AUTO_INCREMENT,
    Nombre_material VARCHAR(20) NOT NULL,
    CODIGO_SAP VARCHAR(20) NOT NULL,
    Serie VARCHAR(20) NOT NULL,
    BODEGA VARCHAR(20) NOT NULL,
    TIPO_MATERIAL VARCHAR(20),
    MARCA_MATERIAL VARCHAR(20),
    MEDIDA DECIMAL(10,2),
    Cantidad_Disponible INT CHECK (Cantidad_Disponible => 0) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS actividad_material (
    ID_ACTIVIDAD_Material INT PRIMARY KEY AUTO_INCREMENT,
    ID_MATERIAL INT NOT NULL,
    ID_ACTIVIDAD INT NOT NULL,
    FOREIGN KEY (ID_MATERIAL) REFERENCES materiales(ID_MATERIAL) ON DELETE CASCADE,
    FOREIGN KEY (ID_ACTIVIDAD) REFERENCES actividad(ID_ACTIVIDAD) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS usuarios (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    Nombre_Usuario VARCHAR(25) NOT NULL,
    CorreoOca VARCHAR(25) NOT NULL,
    contrasena VARCHAR(20) NOT NULL,
    ID_ROL INT NOT NULL,
    CODIGO VARCHAR(20) NOT NULL,
    ESTADO ENUM('activo', 'inactivo') DEFAULT 'activo',
    FOREIGN KEY (ID_ROL) REFERENCES rol(ID_ROL) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS orden_asignada (
    ID_ORDEN_ASIGNADA INT PRIMARY KEY AUTO_INCREMENT,
    ID_ORDEN_TRABAJO INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    FECHA_ASIGNADA DATETIME,
    HORA_ASIGNADA TIME,
    CUADRILLA VARCHAR(25),
    FOREIGN KEY (ID_ORDEN_TRABAJO) REFERENCES orden_trabajo(ID_ORDEN_TRABAJO) ON DELETE CASCADE,
    FOREIGN KEY (ID_USUARIO) REFERENCES usuarios(ID_USUARIO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS material_asignado (
    ID_MATERIAL_ASIGNADO INT PRIMARY KEY AUTO_INCREMENT,
    ID_MATERIAL INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    CANTIDAD_TOTAL INT NOT NULL,
    FECHA DATETIME,
    OBSERVACIONES VARCHAR(25),
    nombreAlmacenista VARCHAR(25) NOT NULL,
    FOREIGN KEY (ID_MATERIAL) REFERENCES materiales(ID_MATERIAL) ON DELETE CASCADE,
    FOREIGN KEY (ID_USUARIO) REFERENCES usuarios(ID_USUARIO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS material_consumido (
    ID_MATERIAL_CONSUMIDO INT PRIMARY KEY AUTO_INCREMENT,
    ID_MATERIAL_ASIGNADO INT NOT NULL,
    CANTIDAD_CONSUMIDA INT CHECK(CANTIDAD_CONSUMIDA => 0) NOT NULL,
    ID_ORDEN_TRABAJO INT NOT NULL,
    FOREIGN KEY (ID_MATERIAL_ASIGNADO) REFERENCES material_asignado(ID_MATERIAL_ASIGNADO) ON DELETE CASCADE,
    FOREIGN KEY (ID_ORDEN_TRABAJO) REFERENCES orden_trabajo(ID_ORDEN_TRABAJO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS material_retirado (
    ID_MATERIAL_RETIRADO INT PRIMARY KEY AUTO_INCREMENT,
    ID_MATERIAL INT NOT NULL,
    Cantidad_Retirada CHECK (Cantidad_Retirada => 0 ) INT,
    numSerie INT NOT NULL,
    ID_ORDEN_TRABAJO INT NOT NULL,
    FOREIGN KEY (ID_MATERIAL) REFERENCES materiales(ID_MATERIAL) ON DELETE CASCADE,
    FOREIGN KEY (ID_ORDEN_TRABAJO) REFERENCES orden_trabajo(ID_ORDEN_TRABAJO) ON  DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS mano_obra (
    ID_MANO_OBRA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_Mano VARCHAR(25) NOT NULL,
    CANTIDAD_PUNTOS INT NOT NULL,
    Valor_Mano_Obra DECIMAL(10,2) CHECK (Valor_Mano_Obra => 0) NOT NULL
);

CREATE TABLE IF NOT EXISTS ManoObra_Trabajo (
    ID_Mano_Obra_Trabajo INT PRIMARY KEY AUTO_INCREMENT,
    ID_MANO_OBRA INT NOT NULL,
    ID_ORDEN_TRABAJO INT NOT NULL,
    ESTADO VARCHAR(20),
    FECHA DATETIME,
    FOREIGN KEY (ID_MANO_OBRA) REFERENCES mano_obra(ID_MANO_OBRA) ON DELETE CASCADE,
    FOREIGN KEY (ID_ORDEN_TRABAJO) REFERENCES orden_trabajo(ID_ORDEN_TRABAJO) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS orden_trabajo (
    ID_ORDEN_TRABAJO INT PRIMARY KEY AUTO_INCREMENT,
    ID_ACTIVIDAD INT NOT NULL,
    NUMERO_ORDEN INT NOT NULL,
    ID_CUENTA_CLIENTE INT NOT NULL,
    ID_DEPARTAMENTO INT NOT NULL,
    ID_CIUDAD INT NOT NULL,
    ID_LOCALIDAD INT NOT NULL,
    ID_ZONA INT NOT NULL,
    FECHA_GENERACION DATETIME,
    FECHA_EJECUCION DATETIME,
    HORA_INICIO TIME,
    HORA_FIN TIME,
    PRIORIDAD VARCHAR(20),
    COORDENADAS VARCHAR(100),
    TOTAL_PUNTOS INT NOT NULL,
    TOTAL_DINERO DECIMAL(20,2) NOT NULL,
    ESTADO VARCHAR(20) NOT NULL,
    OBSERVACION VARCHAR(100),
    BOLSA_SEGURIDAD VARCHAR (30),
    Registro_Fotografico VARCHAR(300), -- Se debe verificar este tipo de dato, y que se puede utilizar el BLOB, 
    -- pero sería para una imagen, no un conjunto de rutas en un objeto. 
    FOREIGN KEY (ID_ACTIVIDAD) REFERENCES actividad(ID_ACTIVIDAD) ON DELETE CASCADE,
    FOREIGN KEY (ID_CUENTA_CLIENTE) REFERENCES cuenta(ID_CUENTA_cliente) ON DELETE CASCADE,
    FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES departamento(ID_DEPARTAMENTO) ON DELETE CASCADE,
    FOREIGN KEY (ID_CIUDAD) REFERENCES ciudad(ID_CIUDAD) ON DELETE CASCADE,
    FOREIGN KEY (ID_LOCALIDAD) REFERENCES localidad(ID_LOCALIDAD) ON DELETE CASCADE,
    FOREIGN KEY (ID_ZONA) REFERENCES zona(ID_ZONA) ON DELETE CASCADE 
);

